language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
before_install: "pip install codecov"
install: "python setup.py install"
script:
  - pip install -r test_requirements.txt
  - py.test --cov=drongo
after_success:
  codecov
